spring:
  kafka:
    topic: topic-first
    groupId: group-2
    bootstrap-servers-main: localhost:9092

services:
  bybit:
    symbol: BTCUSDT, ETHUSDT, BNBUSDT
    interval: 1
    category: linear

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
    bybit.parser: INFO
  file:
    path: log.txt
server:
  port: 9999
