spring:
  kafka:
    topic: topic-first
    groupId: group-2
    bootstrap-servers-main: localhost:9092
    consumer:
      auto-offset-reset: latest
      properties:
        retry.backoff.ms: 1000
        retry.max-attempts: 5

services:
  bybit:
    symbol: BTCUSDT
    interval: 1
    category: linear

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
    bybit.parser: INFO
  file:
    path: log.txt
server:
  port: 9999
